'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()), MySettings)

#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
        Private Shared addedHandler As Boolean

        Private Shared addedHandlerLockObject As New Object

        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
            If My.Application.SaveMySettingsOnExit Then
                My.Settings.Save()
            End If
        End Sub
#End If
#End Region

        Public Shared ReadOnly Property [Default]() As MySettings
            Get

#If _MyType = "WindowsForms" Then
                If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("True")> _
        Public Property mustUpgrade() As Boolean
            Get
                Return CType(Me("mustUpgrade"), Boolean)
            End Get
            Set(value As Boolean)
                Me("mustUpgrade") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property preTensionOfLineValue() As String
            Get
                Return CType(Me("preTensionOfLineValue"), String)
            End Get
            Set(value As String)
                Me("preTensionOfLineValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property preTensionOfLineUnit() As String
            Get
                Return CType(Me("preTensionOfLineUnit"), String)
            End Get
            Set(value As String)
                Me("preTensionOfLineUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property takeOffSpeedValue() As String
            Get
                Return CType(Me("takeOffSpeedValue"), String)
            End Get
            Set(value As String)
                Me("takeOffSpeedValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property takeOffSpeedUnit() As String
            Get
                Return CType(Me("takeOffSpeedUnit"), String)
            End Get
            Set(value As String)
                Me("takeOffSpeedUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property startFlapPosValue() As String
            Get
                Return CType(Me("startFlapPosValue"), String)
            End Get
            Set(value As String)
                Me("startFlapPosValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property startFlapPosUnit() As String
            Get
                Return CType(Me("startFlapPosUnit"), String)
            End Get
            Set(value As String)
                Me("startFlapPosUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property gammaR0Value() As String
            Get
                Return CType(Me("gammaR0Value"), String)
            End Get
            Set(value As String)
                Me("gammaR0Value") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property gammaR0Unit() As String
            Get
                Return CType(Me("gammaR0Unit"), String)
            End Get
            Set(value As String)
                Me("gammaR0Unit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property gammaR1Value() As String
            Get
                Return CType(Me("gammaR1Value"), String)
            End Get
            Set(value As String)
                Me("gammaR1Value") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property gammaR1Unit() As String
            Get
                Return CType(Me("gammaR1Unit"), String)
            End Get
            Set(value As String)
                Me("gammaR1Unit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property gammaR2Value() As String
            Get
                Return CType(Me("gammaR2Value"), String)
            End Get
            Set(value As String)
                Me("gammaR2Value") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property gammaR2Unit() As String
            Get
                Return CType(Me("gammaR2Unit"), String)
            End Get
            Set(value As String)
                Me("gammaR2Unit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property gammaR3Value() As String
            Get
                Return CType(Me("gammaR3Value"), String)
            End Get
            Set(value As String)
                Me("gammaR3Value") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property gammaR3Unit() As String
            Get
                Return CType(Me("gammaR3Unit"), String)
            End Get
            Set(value As String)
                Me("gammaR3Unit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property diveStartAngleValue() As String
            Get
                Return CType(Me("diveStartAngleValue"), String)
            End Get
            Set(value As String)
                Me("diveStartAngleValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property diveStartAngleUnit() As String
            Get
                Return CType(Me("diveStartAngleUnit"), String)
            End Get
            Set(value As String)
                Me("diveStartAngleUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property speedFlapPosValue() As String
            Get
                Return CType(Me("speedFlapPosValue"), String)
            End Get
            Set(value As String)
                Me("speedFlapPosValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property speedFlapPosUnit() As String
            Get
                Return CType(Me("speedFlapPosUnit"), String)
            End Get
            Set(value As String)
                Me("speedFlapPosUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property climbAngleValue() As String
            Get
                Return CType(Me("climbAngleValue"), String)
            End Get
            Set(value As String)
                Me("climbAngleValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property climbAngleUnit() As String
            Get
                Return CType(Me("climbAngleUnit"), String)
            End Get
            Set(value As String)
                Me("climbAngleUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property wingSpanValue() As String
            Get
                Return CType(Me("wingSpanValue"), String)
            End Get
            Set(value As String)
                Me("wingSpanValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property wingSpanUnit() As String
            Get
                Return CType(Me("wingSpanUnit"), String)
            End Get
            Set(value As String)
                Me("wingSpanUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property wingLoadingValue() As String
            Get
                Return CType(Me("wingLoadingValue"), String)
            End Get
            Set(value As String)
                Me("wingLoadingValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property wingLoadingUnit() As String
            Get
                Return CType(Me("wingLoadingUnit"), String)
            End Get
            Set(value As String)
                Me("wingLoadingUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property ARValue() As String
            Get
                Return CType(Me("ARValue"), String)
            End Get
            Set(value As String)
                Me("ARValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property ARUnit() As String
            Get
                Return CType(Me("ARUnit"), String)
            End Get
            Set(value As String)
                Me("ARUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property refReValue() As String
            Get
                Return CType(Me("refReValue"), String)
            End Get
            Set(value As String)
                Me("refReValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property refReUnit() As String
            Get
                Return CType(Me("refReUnit"), String)
            End Get
            Set(value As String)
                Me("refReUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property cdInferenceValue() As String
            Get
                Return CType(Me("cdInferenceValue"), String)
            End Get
            Set(value As String)
                Me("cdInferenceValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property cdInferenceUnit() As String
            Get
                Return CType(Me("cdInferenceUnit"), String)
            End Get
            Set(value As String)
                Me("cdInferenceUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property cdInducedFactorValue() As String
            Get
                Return CType(Me("cdInducedFactorValue"), String)
            End Get
            Set(value As String)
                Me("cdInducedFactorValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property cdInducedFactorUnit() As String
            Get
                Return CType(Me("cdInducedFactorUnit"), String)
            End Get
            Set(value As String)
                Me("cdInducedFactorUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property cdParasiticSpeedFlapValue() As String
            Get
                Return CType(Me("cdParasiticSpeedFlapValue"), String)
            End Get
            Set(value As String)
                Me("cdParasiticSpeedFlapValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property cdParasiticSpeedFlapUnit() As String
            Get
                Return CType(Me("cdParasiticSpeedFlapUnit"), String)
            End Get
            Set(value As String)
                Me("cdParasiticSpeedFlapUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property cdParasiticStartFlapValue() As String
            Get
                Return CType(Me("cdParasiticStartFlapValue"), String)
            End Get
            Set(value As String)
                Me("cdParasiticStartFlapValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property cdParasiticStartFlapUnit() As String
            Get
                Return CType(Me("cdParasiticStartFlapUnit"), String)
            End Get
            Set(value As String)
                Me("cdParasiticStartFlapUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property clAlphaCoeffValue() As String
            Get
                Return CType(Me("clAlphaCoeffValue"), String)
            End Get
            Set(value As String)
                Me("clAlphaCoeffValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property clAlphaCoeffUnit() As String
            Get
                Return CType(Me("clAlphaCoeffUnit"), String)
            End Get
            Set(value As String)
                Me("clAlphaCoeffUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property maxLoadFactorValue() As String
            Get
                Return CType(Me("maxLoadFactorValue"), String)
            End Get
            Set(value As String)
                Me("maxLoadFactorValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property maxLoadFactorUnit() As String
            Get
                Return CType(Me("maxLoadFactorUnit"), String)
            End Get
            Set(value As String)
                Me("maxLoadFactorUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property speedFlapCl0Value() As String
            Get
                Return CType(Me("speedFlapCl0Value"), String)
            End Get
            Set(value As String)
                Me("speedFlapCl0Value") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property speedFlapCl0Unit() As String
            Get
                Return CType(Me("speedFlapCl0Unit"), String)
            End Get
            Set(value As String)
                Me("speedFlapCl0Unit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property startFlapCl0Value() As String
            Get
                Return CType(Me("startFlapCl0Value"), String)
            End Get
            Set(value As String)
                Me("startFlapCl0Value") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property startFlapCl0Unit() As String
            Get
                Return CType(Me("startFlapCl0Unit"), String)
            End Get
            Set(value As String)
                Me("startFlapCl0Unit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property reCoeffValue() As String
            Get
                Return CType(Me("reCoeffValue"), String)
            End Get
            Set(value As String)
                Me("reCoeffValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property reCoeffUnit() As String
            Get
                Return CType(Me("reCoeffUnit"), String)
            End Get
            Set(value As String)
                Me("reCoeffUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property drumDiameterValue() As String
            Get
                Return CType(Me("drumDiameterValue"), String)
            End Get
            Set(value As String)
                Me("drumDiameterValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property drumDiameterUnit() As String
            Get
                Return CType(Me("drumDiameterUnit"), String)
            End Get
            Set(value As String)
                Me("drumDiameterUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property drumLengthValue() As String
            Get
                Return CType(Me("drumLengthValue"), String)
            End Get
            Set(value As String)
                Me("drumLengthValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property drumLengthUnit() As String
            Get
                Return CType(Me("drumLengthUnit"), String)
            End Get
            Set(value As String)
                Me("drumLengthUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property wstValue() As String
            Get
                Return CType(Me("wstValue"), String)
            End Get
            Set(value As String)
                Me("wstValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property wstUnit() As String
            Get
                Return CType(Me("wstUnit"), String)
            End Get
            Set(value As String)
                Me("wstUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property wzsValue() As String
            Get
                Return CType(Me("wzsValue"), String)
            End Get
            Set(value As String)
                Me("wzsValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property wzsUnit() As String
            Get
                Return CType(Me("wzsUnit"), String)
            End Get
            Set(value As String)
                Me("wzsUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property distanceToPulleyValue() As String
            Get
                Return CType(Me("distanceToPulleyValue"), String)
            End Get
            Set(value As String)
                Me("distanceToPulleyValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property distanceToPulleyUnit() As String
            Get
                Return CType(Me("distanceToPulleyUnit"), String)
            End Get
            Set(value As String)
                Me("distanceToPulleyUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property windSpeedValue() As String
            Get
                Return CType(Me("windSpeedValue"), String)
            End Get
            Set(value As String)
                Me("windSpeedValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property windSpeedUnit() As String
            Get
                Return CType(Me("windSpeedUnit"), String)
            End Get
            Set(value As String)
                Me("windSpeedUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property thermicCeilValue() As String
            Get
                Return CType(Me("thermicCeilValue"), String)
            End Get
            Set(value As String)
                Me("thermicCeilValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property thermicCeilUnit() As String
            Get
                Return CType(Me("thermicCeilUnit"), String)
            End Get
            Set(value As String)
                Me("thermicCeilUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property thermicValue() As String
            Get
                Return CType(Me("thermicValue"), String)
            End Get
            Set(value As String)
                Me("thermicValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property thermicUnit() As String
            Get
                Return CType(Me("thermicUnit"), String)
            End Get
            Set(value As String)
                Me("thermicUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property tempAtGroundValue() As String
            Get
                Return CType(Me("tempAtGroundValue"), String)
            End Get
            Set(value As String)
                Me("tempAtGroundValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property tempAtGroundUnit() As String
            Get
                Return CType(Me("tempAtGroundUnit"), String)
            End Get
            Set(value As String)
                Me("tempAtGroundUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property pressureAtGroundValue() As String
            Get
                Return CType(Me("pressureAtGroundValue"), String)
            End Get
            Set(value As String)
                Me("pressureAtGroundValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property pressureAtGroundUnit() As String
            Get
                Return CType(Me("pressureAtGroundUnit"), String)
            End Get
            Set(value As String)
                Me("pressureAtGroundUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property humidityValue() As String
            Get
                Return CType(Me("humidityValue"), String)
            End Get
            Set(value As String)
                Me("humidityValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property humidityUnit() As String
            Get
                Return CType(Me("humidityUnit"), String)
            End Get
            Set(value As String)
                Me("humidityUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property lineDiameterValue() As String
            Get
                Return CType(Me("lineDiameterValue"), String)
            End Get
            Set(value As String)
                Me("lineDiameterValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property lineDiameterUnit() As String
            Get
                Return CType(Me("lineDiameterUnit"), String)
            End Get
            Set(value As String)
                Me("lineDiameterUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property totalLineLengthValue() As String
            Get
                Return CType(Me("totalLineLengthValue"), String)
            End Get
            Set(value As String)
                Me("totalLineLengthValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property totalLineLengthUnit() As String
            Get
                Return CType(Me("totalLineLengthUnit"), String)
            End Get
            Set(value As String)
                Me("totalLineLengthUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property EModuleValue() As String
            Get
                Return CType(Me("EModuleValue"), String)
            End Get
            Set(value As String)
                Me("EModuleValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property EModuleUnit() As String
            Get
                Return CType(Me("EModuleUnit"), String)
            End Get
            Set(value As String)
                Me("EModuleUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property lineDragCoefficientValue() As String
            Get
                Return CType(Me("lineDragCoefficientValue"), String)
            End Get
            Set(value As String)
                Me("lineDragCoefficientValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property lineDragCoefficientUnit() As String
            Get
                Return CType(Me("lineDragCoefficientUnit"), String)
            End Get
            Set(value As String)
                Me("lineDragCoefficientUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property parachuteDragCoeffcientValue() As String
            Get
                Return CType(Me("parachuteDragCoeffcientValue"), String)
            End Get
            Set(value As String)
                Me("parachuteDragCoeffcientValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property parachuteDragCoeffcientUnit() As String
            Get
                Return CType(Me("parachuteDragCoeffcientUnit"), String)
            End Get
            Set(value As String)
                Me("parachuteDragCoeffcientUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property parachuteAreaValue() As String
            Get
                Return CType(Me("parachuteAreaValue"), String)
            End Get
            Set(value As String)
                Me("parachuteAreaValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property parachuteAreaUnit() As String
            Get
                Return CType(Me("parachuteAreaUnit"), String)
            End Get
            Set(value As String)
                Me("parachuteAreaUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property dtValue() As String
            Get
                Return CType(Me("dtValue"), String)
            End Get
            Set(value As String)
                Me("dtValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property dtUnit() As String
            Get
                Return CType(Me("dtUnit"), String)
            End Get
            Set(value As String)
                Me("dtUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property maxTValue() As String
            Get
                Return CType(Me("maxTValue"), String)
            End Get
            Set(value As String)
                Me("maxTValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property maxTUnit() As String
            Get
                Return CType(Me("maxTUnit"), String)
            End Get
            Set(value As String)
                Me("maxTUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property launchAngleValue() As String
            Get
                Return CType(Me("launchAngleValue"), String)
            End Get
            Set(value As String)
                Me("launchAngleValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property launchAngleUnit() As String
            Get
                Return CType(Me("launchAngleUnit"), String)
            End Get
            Set(value As String)
                Me("launchAngleUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property setpointAOAValue() As String
            Get
                Return CType(Me("setpointAOAValue"), String)
            End Get
            Set(value As String)
                Me("setpointAOAValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property setpointAOAUnit() As String
            Get
                Return CType(Me("setpointAOAUnit"), String)
            End Get
            Set(value As String)
                Me("setpointAOAUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outgroundSpeedXValue() As String
            Get
                Return CType(Me("outgroundSpeedXValue"), String)
            End Get
            Set(value As String)
                Me("outgroundSpeedXValue") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outgroundSpeedXUnit() As String
            Get
                Return CType(Me("outgroundSpeedXUnit"), String)
            End Get
            Set(value As String)
                Me("outgroundSpeedXUnit") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outvValue() As String
            Get
                Return CType(Me("outvValue"), String)
            End Get
            Set(value As String)
                Me("outvValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outvUnit() As String
            Get
                Return CType(Me("outvUnit"), String)
            End Get
            Set(value As String)
                Me("outvUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outaxValue() As String
            Get
                Return CType(Me("outaxValue"), String)
            End Get
            Set(value As String)
                Me("outaxValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outaxUnit() As String
            Get
                Return CType(Me("outaxUnit"), String)
            End Get
            Set(value As String)
                Me("outaxUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outayValue() As String
            Get
                Return CType(Me("outayValue"), String)
            End Get
            Set(value As String)
                Me("outayValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outayUnit() As String
            Get
                Return CType(Me("outayUnit"), String)
            End Get
            Set(value As String)
                Me("outayUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outxValue() As String
            Get
                Return CType(Me("outxValue"), String)
            End Get
            Set(value As String)
                Me("outxValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outxUnit() As String
            Get
                Return CType(Me("outxUnit"), String)
            End Get
            Set(value As String)
                Me("outxUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outyValue() As String
            Get
                Return CType(Me("outyValue"), String)
            End Get
            Set(value As String)
                Me("outyValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outyUnit() As String
            Get
                Return CType(Me("outyUnit"), String)
            End Get
            Set(value As String)
                Me("outyUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outfxValue() As String
            Get
                Return CType(Me("outfxValue"), String)
            End Get
            Set(value As String)
                Me("outfxValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outfxUnit() As String
            Get
                Return CType(Me("outfxUnit"), String)
            End Get
            Set(value As String)
                Me("outfxUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outfyValue() As String
            Get
                Return CType(Me("outfyValue"), String)
            End Get
            Set(value As String)
                Me("outfyValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outfyUnit() As String
            Get
                Return CType(Me("outfyUnit"), String)
            End Get
            Set(value As String)
                Me("outfyUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outtotalLineLengthValue() As String
            Get
                Return CType(Me("outtotalLineLengthValue"), String)
            End Get
            Set(value As String)
                Me("outtotalLineLengthValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outtotalLineLengthUnit() As String
            Get
                Return CType(Me("outtotalLineLengthUnit"), String)
            End Get
            Set(value As String)
                Me("outtotalLineLengthUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outclTotalValue() As String
            Get
                Return CType(Me("outclTotalValue"), String)
            End Get
            Set(value As String)
                Me("outclTotalValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outclTotalUnit() As String
            Get
                Return CType(Me("outclTotalUnit"), String)
            End Get
            Set(value As String)
                Me("outclTotalUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outcdTotalValue() As String
            Get
                Return CType(Me("outcdTotalValue"), String)
            End Get
            Set(value As String)
                Me("outcdTotalValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outcdTotalUnit() As String
            Get
                Return CType(Me("outcdTotalUnit"), String)
            End Get
            Set(value As String)
                Me("outcdTotalUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outfDragValue() As String
            Get
                Return CType(Me("outfDragValue"), String)
            End Get
            Set(value As String)
                Me("outfDragValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outfDragUnit() As String
            Get
                Return CType(Me("outfDragUnit"), String)
            End Get
            Set(value As String)
                Me("outfDragUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outfLiftValue() As String
            Get
                Return CType(Me("outfLiftValue"), String)
            End Get
            Set(value As String)
                Me("outfLiftValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outfLiftUnit() As String
            Get
                Return CType(Me("outfLiftUnit"), String)
            End Get
            Set(value As String)
                Me("outfLiftUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outlineForceValue() As String
            Get
                Return CType(Me("outlineForceValue"), String)
            End Get
            Set(value As String)
                Me("outlineForceValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outlineForceUnit() As String
            Get
                Return CType(Me("outlineForceUnit"), String)
            End Get
            Set(value As String)
                Me("outlineForceUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outkLineValue() As String
            Get
                Return CType(Me("outkLineValue"), String)
            End Get
            Set(value As String)
                Me("outkLineValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outkLineUnit() As String
            Get
                Return CType(Me("outkLineUnit"), String)
            End Get
            Set(value As String)
                Me("outkLineUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outlineDiameterValue() As String
            Get
                Return CType(Me("outlineDiameterValue"), String)
            End Get
            Set(value As String)
                Me("outlineDiameterValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outlineDiameterUnit() As String
            Get
                Return CType(Me("outlineDiameterUnit"), String)
            End Get
            Set(value As String)
                Me("outlineDiameterUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outlineOnWinchValue() As String
            Get
                Return CType(Me("outlineOnWinchValue"), String)
            End Get
            Set(value As String)
                Me("outlineOnWinchValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outlineOnWinchUnit() As String
            Get
                Return CType(Me("outlineOnWinchUnit"), String)
            End Get
            Set(value As String)
                Me("outlineOnWinchUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outlengthToPlaneFromPulleyValue() As String
            Get
                Return CType(Me("outlengthToPlaneFromPulleyValue"), String)
            End Get
            Set(value As String)
                Me("outlengthToPlaneFromPulleyValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outlengthToPlaneFromPulleyUnit() As String
            Get
                Return CType(Me("outlengthToPlaneFromPulleyUnit"), String)
            End Get
            Set(value As String)
                Me("outlengthToPlaneFromPulleyUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outlineAreaValue() As String
            Get
                Return CType(Me("outlineAreaValue"), String)
            End Get
            Set(value As String)
                Me("outlineAreaValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outlineAreaUnit() As String
            Get
                Return CType(Me("outlineAreaUnit"), String)
            End Get
            Set(value As String)
                Me("outlineAreaUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outlineDragValue() As String
            Get
                Return CType(Me("outlineDragValue"), String)
            End Get
            Set(value As String)
                Me("outlineDragValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outlineDragUnit() As String
            Get
                Return CType(Me("outlineDragUnit"), String)
            End Get
            Set(value As String)
                Me("outlineDragUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outfTotalDragValue() As String
            Get
                Return CType(Me("outfTotalDragValue"), String)
            End Get
            Set(value As String)
                Me("outfTotalDragValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outfTotalDragUnit() As String
            Get
                Return CType(Me("outfTotalDragUnit"), String)
            End Get
            Set(value As String)
                Me("outfTotalDragUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outdeltaLineLengthValue() As String
            Get
                Return CType(Me("outdeltaLineLengthValue"), String)
            End Get
            Set(value As String)
                Me("outdeltaLineLengthValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outdeltaLineLengthUnit() As String
            Get
                Return CType(Me("outdeltaLineLengthUnit"), String)
            End Get
            Set(value As String)
                Me("outdeltaLineLengthUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outwindSpeedValue() As String
            Get
                Return CType(Me("outwindSpeedValue"), String)
            End Get
            Set(value As String)
                Me("outwindSpeedValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outwindSpeedUnit() As String
            Get
                Return CType(Me("outwindSpeedUnit"), String)
            End Get
            Set(value As String)
                Me("outwindSpeedUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outphaseValue() As String
            Get
                Return CType(Me("outphaseValue"), String)
            End Get
            Set(value As String)
                Me("outphaseValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outphaseUnit() As String
            Get
                Return CType(Me("outphaseUnit"), String)
            End Get
            Set(value As String)
                Me("outphaseUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outgammaValue() As String
            Get
                Return CType(Me("outgammaValue"), String)
            End Get
            Set(value As String)
                Me("outgammaValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outgammaUnit() As String
            Get
                Return CType(Me("outgammaUnit"), String)
            End Get
            Set(value As String)
                Me("outgammaUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outtimeValue() As String
            Get
                Return CType(Me("outtimeValue"), String)
            End Get
            Set(value As String)
                Me("outtimeValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outtimeUnit() As String
            Get
                Return CType(Me("outtimeUnit"), String)
            End Get
            Set(value As String)
                Me("outtimeUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outrhoValue() As String
            Get
                Return CType(Me("outrhoValue"), String)
            End Get
            Set(value As String)
                Me("outrhoValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outrhoUnit() As String
            Get
                Return CType(Me("outrhoUnit"), String)
            End Get
            Set(value As String)
                Me("outrhoUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outpsiValue() As String
            Get
                Return CType(Me("outpsiValue"), String)
            End Get
            Set(value As String)
                Me("outpsiValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outpsiUnit() As String
            Get
                Return CType(Me("outpsiUnit"), String)
            End Get
            Set(value As String)
                Me("outpsiUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outvelAngValue() As String
            Get
                Return CType(Me("outvelAngValue"), String)
            End Get
            Set(value As String)
                Me("outvelAngValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outvelAngUnit() As String
            Get
                Return CType(Me("outvelAngUnit"), String)
            End Get
            Set(value As String)
                Me("outvelAngUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outattAngValue() As String
            Get
                Return CType(Me("outattAngValue"), String)
            End Get
            Set(value As String)
                Me("outattAngValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outattAngUnit() As String
            Get
                Return CType(Me("outattAngUnit"), String)
            End Get
            Set(value As String)
                Me("outattAngUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outtemperatureValue() As String
            Get
                Return CType(Me("outtemperatureValue"), String)
            End Get
            Set(value As String)
                Me("outtemperatureValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outtemperatureUnit() As String
            Get
                Return CType(Me("outtemperatureUnit"), String)
            End Get
            Set(value As String)
                Me("outtemperatureUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outnuValue() As String
            Get
                Return CType(Me("outnuValue"), String)
            End Get
            Set(value As String)
                Me("outnuValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outnuUnit() As String
            Get
                Return CType(Me("outnuUnit"), String)
            End Get
            Set(value As String)
                Me("outnuUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outReValue() As String
            Get
                Return CType(Me("outReValue"), String)
            End Get
            Set(value As String)
                Me("outReValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outReUnit() As String
            Get
                Return CType(Me("outReUnit"), String)
            End Get
            Set(value As String)
                Me("outReUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outflapPosValue() As String
            Get
                Return CType(Me("outflapPosValue"), String)
            End Get
            Set(value As String)
                Me("outflapPosValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outflapPosUnit() As String
            Get
                Return CType(Me("outflapPosUnit"), String)
            End Get
            Set(value As String)
                Me("outflapPosUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outcdLineValue() As String
            Get
                Return CType(Me("outcdLineValue"), String)
            End Get
            Set(value As String)
                Me("outcdLineValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outcdLineUnit() As String
            Get
                Return CType(Me("outcdLineUnit"), String)
            End Get
            Set(value As String)
                Me("outcdLineUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outmomentOnWinchDrumValue() As String
            Get
                Return CType(Me("outmomentOnWinchDrumValue"), String)
            End Get
            Set(value As String)
                Me("outmomentOnWinchDrumValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outmomentOnWinchDrumUnit() As String
            Get
                Return CType(Me("outmomentOnWinchDrumUnit"), String)
            End Get
            Set(value As String)
                Me("outmomentOnWinchDrumUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outdrumDiameterValue() As String
            Get
                Return CType(Me("outdrumDiameterValue"), String)
            End Get
            Set(value As String)
                Me("outdrumDiameterValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outdrumDiameterUnit() As String
            Get
                Return CType(Me("outdrumDiameterUnit"), String)
            End Get
            Set(value As String)
                Me("outdrumDiameterUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outsValue() As String
            Get
                Return CType(Me("outsValue"), String)
            End Get
            Set(value As String)
                Me("outsValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outsUnit() As String
            Get
                Return CType(Me("outsUnit"), String)
            End Get
            Set(value As String)
                Me("outsUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outairSpeedValue() As String
            Get
                Return CType(Me("outairSpeedValue"), String)
            End Get
            Set(value As String)
                Me("outairSpeedValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outairSpeedUnit() As String
            Get
                Return CType(Me("outairSpeedUnit"), String)
            End Get
            Set(value As String)
                Me("outairSpeedUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outairSpeedXValue() As String
            Get
                Return CType(Me("outairSpeedXValue"), String)
            End Get
            Set(value As String)
                Me("outairSpeedXValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outairSpeedYValue() As String
            Get
                Return CType(Me("outairSpeedYValue"), String)
            End Get
            Set(value As String)
                Me("outairSpeedYValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outairSpeedYUnit() As String
            Get
                Return CType(Me("outairSpeedYUnit"), String)
            End Get
            Set(value As String)
                Me("outairSpeedYUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outgroundSpeedValue() As String
            Get
                Return CType(Me("outgroundSpeedValue"), String)
            End Get
            Set(value As String)
                Me("outgroundSpeedValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outgroundSpeedUnit() As String
            Get
                Return CType(Me("outgroundSpeedUnit"), String)
            End Get
            Set(value As String)
                Me("outgroundSpeedUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outairSpeedXUnit() As String
            Get
                Return CType(Me("outairSpeedXUnit"), String)
            End Get
            Set(value As String)
                Me("outairSpeedXUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property varyMin() As String
            Get
                Return CType(Me("varyMin"), String)
            End Get
            Set(value As String)
                Me("varyMin") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("0")> _
        Public Property varyMax() As String
            Get
                Return CType(Me("varyMax"), String)
            End Get
            Set(value As String)
                Me("varyMax") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property varySteps() As String
            Get
                Return CType(Me("varySteps"), String)
            End Get
            Set(value As String)
                Me("varySteps") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property varyParameter() As String
            Get
                Return CType(Me("varyParameter"), String)
            End Get
            Set(value As String)
                Me("varyParameter") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property poissonRatioValue() As String
            Get
                Return CType(Me("poissonRatioValue"), String)
            End Get
            Set(value As String)
                Me("poissonRatioValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property poissonRatioUnit() As String
            Get
                Return CType(Me("poissonRatioUnit"), String)
            End Get
            Set(value As String)
                Me("poissonRatioUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outverticalWindSpeedValue() As String
            Get
                Return CType(Me("outverticalWindSpeedValue"), String)
            End Get
            Set(value As String)
                Me("outverticalWindSpeedValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outverticalWindSpeedUnit() As String
            Get
                Return CType(Me("outverticalWindSpeedUnit"), String)
            End Get
            Set(value As String)
                Me("outverticalWindSpeedUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outhorisontalWindSpeedValue() As String
            Get
                Return CType(Me("outhorisontalWindSpeedValue"), String)
            End Get
            Set(value As String)
                Me("outhorisontalWindSpeedValue") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property outhorisontalWindSpeedUnit() As String
            Get
                Return CType(Me("outhorisontalWindSpeedUnit"), String)
            End Get
            Set(value As String)
                Me("outhorisontalWindSpeedUnit") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property lastVersion() As String
            Get
                Return CType(Me("lastVersion"), String)
            End Get
            Set(value As String)
                Me("lastVersion") = Value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SailPlaneLaunch.My.MySettings
            Get
                Return Global.SailPlaneLaunch.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
